import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import logoMarca from "../../public/logomarca.png";
import NavBar from "@/components/navBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet" />
      </head>
      <body className="h-screen w-screen">
        <header className="flex justify-between items-center h-24 w-full bg-[#418713] p-10">
          <Image className="h-16 w-auto" src={logoMarca} alt="VerdeCard" />
        </header>
        <main className="flex justify-center items-center h-[calc(100vh-96px)] bg-[#d2d2d2]">
          {children}
        </main>
      </body>
    </html>
  );
}
